<?php
/* Cyrillic Charset class - Generated by katmore/rand-string/bin/make-charset.php
 * - Template: 0.0.3
 * - Codepoints: U+0030 to U+003F, U+0410 to U+044F
 * - Upper-Letters etag: a5092e53c9bbadbd24ef5ccddbabea6d
 * - Lower-Letters etag: caa49e28db8ae0b6182fc57dc0374637
 * - Digits etag: ddc8a93348447e44ad1cfc6f7a43988e
 */
namespace IntlRandString\Charset;

use IntlRandString\Charset;

class Cyrillic extends Charset {

   const UPPER_LETTERS = [
      'А',
      'Б',
      'В',
      'Г',
      'Д',
      'Е',
      'Ж',
      'З',
      'И',
      'Й',
      'К',
      'Л',
      'М',
      'Н',
      'О',
      'П',
      'Р',
      'С',
      'Т',
      'У',
      'Ф',
      'Х',
      'Ц',
      'Ч',
      'Ш',
      'Щ',
      'Ъ',
      'Ы',
      'Ь',
      'Э',
      'Ю',
      'Я',
   ];

   const LOWER_LETTERS = [
      'а',
      'б',
      'в',
      'г',
      'д',
      'е',
      'ж',
      'з',
      'и',
      'й',
      'к',
      'л',
      'м',
      'н',
      'о',
      'п',
      'р',
      'с',
      'т',
      'у',
      'ф',
      'х',
      'ц',
      'ч',
      'ш',
      'щ',
      'ъ',
      'ы',
      'ь',
      'э',
      'ю',
      'я',
   ];

   const DIGITS = [
      '0',
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
   ];

   public static function enumUpperLetters() : array { return static::UPPER_LETTERS; }
   public static function enumLowerLetters() : array { return static::LOWER_LETTERS; }
   public static function enumDigits() : array { return static::DIGITS; }
}
