<?php
/* English Charset class - Generated by katmore/rand-string/bin/make-charset.php
 * - Template: 0.0.3
 * - Codepoints: U+0030 to U+003F, U+0041 to U+005A, U+0061 to U+007A
 * - Upper-Letters etag: 87bd7dd442c22e3fbee3b80d44b09b65
 * - Lower-Letters etag: d3012541c8ed21a97981aa6a8d861060
 * - Digits etag: ddc8a93348447e44ad1cfc6f7a43988e
 */
namespace IntlRandString\Charset;

use IntlRandString\Charset;

class English extends Charset {

   const UPPER_LETTERS = [
      'A',
      'B',
      'C',
      'D',
      'E',
      'F',
      'G',
      'H',
      'I',
      'J',
      'K',
      'L',
      'M',
      'N',
      'O',
      'P',
      'Q',
      'R',
      'S',
      'T',
      'U',
      'V',
      'W',
      'X',
      'Y',
      'Z',
   ];

   const LOWER_LETTERS = [
      'a',
      'b',
      'c',
      'd',
      'e',
      'f',
      'g',
      'h',
      'i',
      'j',
      'k',
      'l',
      'm',
      'n',
      'o',
      'p',
      'q',
      'r',
      's',
      't',
      'u',
      'v',
      'w',
      'x',
      'y',
      'z',
   ];

   const DIGITS = [
      '0',
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
   ];

   public static function enumUpperLetters() : array { return static::UPPER_LETTERS; }
   public static function enumLowerLetters() : array { return static::LOWER_LETTERS; }
   public static function enumDigits() : array { return static::DIGITS; }
}
