<?php
/* German Charset class - Generated by katmore/rand-string/bin/make-charset.php
 * - Template: 0.0.3
 * - Codepoints: U+0030 to U+003F, U+0041 to U+005A, U+0061 to U+007A, U+00E4 to U+00E4, U+00F6 to U+00F6, U+00FC to U+00FC, U+00C4 to U+00C4, U+00D6 to U+00D6, U+00DC to U+00DC, U+00DF to U+00DF, U+1E9E to U+1E9E
 * - Upper-Letters etag: 6f2cc51f788f360077a6cc496e3d3975
 * - Lower-Letters etag: d0cc1141b930ad484f994c00cf85b47e
 * - Digits etag: ddc8a93348447e44ad1cfc6f7a43988e
 */
namespace IntlRandString\Charset;

use IntlRandString\Charset;

class German extends Charset {

   const UPPER_LETTERS = [
      'A',
      'B',
      'C',
      'D',
      'E',
      'F',
      'G',
      'H',
      'I',
      'J',
      'K',
      'L',
      'M',
      'N',
      'O',
      'P',
      'Q',
      'R',
      'S',
      'T',
      'U',
      'V',
      'W',
      'X',
      'Y',
      'Z',
      'Ä',
      'Ö',
      'Ü',
      'ẞ',
   ];

   const LOWER_LETTERS = [
      'a',
      'b',
      'c',
      'd',
      'e',
      'f',
      'g',
      'h',
      'i',
      'j',
      'k',
      'l',
      'm',
      'n',
      'o',
      'p',
      'q',
      'r',
      's',
      't',
      'u',
      'v',
      'w',
      'x',
      'y',
      'z',
      'ä',
      'ö',
      'ü',
      'ß',
   ];

   const DIGITS = [
      '0',
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
   ];

   public static function enumUpperLetters() : array { return static::UPPER_LETTERS; }
   public static function enumLowerLetters() : array { return static::LOWER_LETTERS; }
   public static function enumDigits() : array { return static::DIGITS; }
}
