<?php
/* Italian Charset class - Generated by katmore/rand-string/bin/make-charset.php
 * - Template: 0.0.3
 * - Codepoints: U+0030 to U+003F, U+0061 to U+006A, U+0041 to U+004A, U+006C to U+0076, U+004C to U+0056, U+007A to U+007A, U+005A to U+005A
 * - Upper-Letters etag: 24f97e8ebca53692fad366e09c4a443e
 * - Lower-Letters etag: 6876cc2f1ad94d1e8e3e08e3566c1d34
 * - Digits etag: ddc8a93348447e44ad1cfc6f7a43988e
 */
namespace IntlRandString\Charset;

use IntlRandString\Charset;

class Italian extends Charset {

   const UPPER_LETTERS = [
      'A',
      'B',
      'C',
      'D',
      'E',
      'F',
      'G',
      'H',
      'I',
      'J',
      'L',
      'M',
      'N',
      'O',
      'P',
      'Q',
      'R',
      'S',
      'T',
      'U',
      'V',
      'Z',
   ];

   const LOWER_LETTERS = [
      'a',
      'b',
      'c',
      'd',
      'e',
      'f',
      'g',
      'h',
      'i',
      'j',
      'l',
      'm',
      'n',
      'o',
      'p',
      'q',
      'r',
      's',
      't',
      'u',
      'v',
      'z',
   ];

   const DIGITS = [
      '0',
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
   ];

   public static function enumUpperLetters() : array { return static::UPPER_LETTERS; }
   public static function enumLowerLetters() : array { return static::LOWER_LETTERS; }
   public static function enumDigits() : array { return static::DIGITS; }
}
