<?php
/* Spanish Charset class - Generated by katmore/rand-string/bin/make-charset.php
 * - Template: 0.0.3
 * - Codepoints: U+0030 to U+003F, U+0041 to U+005A, U+0061 to U+007A, U+00E1 to U+00E1, U+00E9 to U+00E9, U+00ED to U+00ED, U+00F3 to U+00F3, U+00FA to U+00FA, U+00C1 to U+00C1, U+00C9 to U+00C9, U+00CD to U+00CD, U+00D3 to U+00D3, U+00DA to U+00DA, U+00F1 to U+00F1, U+00D1 to U+00D1
 * - Upper-Letters etag: cc0e9a2c37632849c65aa88638f59879
 * - Lower-Letters etag: ab370d85537c64f35c9f95ba9b59d1d0
 * - Digits etag: ddc8a93348447e44ad1cfc6f7a43988e
 */
namespace IntlRandString\Charset;

use IntlRandString\Charset;

class Spanish extends Charset {

   const UPPER_LETTERS = [
      'A',
      'B',
      'C',
      'D',
      'E',
      'F',
      'G',
      'H',
      'I',
      'J',
      'K',
      'L',
      'M',
      'N',
      'O',
      'P',
      'Q',
      'R',
      'S',
      'T',
      'U',
      'V',
      'W',
      'X',
      'Y',
      'Z',
      'Á',
      'É',
      'Í',
      'Ó',
      'Ú',
      'Ñ',
   ];

   const LOWER_LETTERS = [
      'a',
      'b',
      'c',
      'd',
      'e',
      'f',
      'g',
      'h',
      'i',
      'j',
      'k',
      'l',
      'm',
      'n',
      'o',
      'p',
      'q',
      'r',
      's',
      't',
      'u',
      'v',
      'w',
      'x',
      'y',
      'z',
      'á',
      'é',
      'í',
      'ó',
      'ú',
      'ñ',
   ];

   const DIGITS = [
      '0',
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
   ];

   public static function enumUpperLetters() : array { return static::UPPER_LETTERS; }
   public static function enumLowerLetters() : array { return static::LOWER_LETTERS; }
   public static function enumDigits() : array { return static::DIGITS; }
}
